name: CI - Build Docker

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run unit tests
        run: |
          # run all tests (this repository has no library target)
          cargo test --all

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      CARGO_BINSTALL_VERSION: "v0"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown || true

      - name: Cache cargo bin (separate, keyed by cargo-binstall version)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ env.CARGO_BINSTALL_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-${{ env.CARGO_BINSTALL_VERSION }}-

      - name: Cache cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Install cargo-binstall via official installer script
        run: |
          echo "Downloading official cargo-binstall installer script"
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh -o /tmp/install-binstall.sh
          chmod +x /tmp/install-binstall.sh
          echo "Running cargo-binstall installer"
          /tmp/install-binstall.sh

      - name: Use cargo-binstall to install dioxus-cli
        run: |
          cargo binstall dioxus-cli

      - name: Bundle web assets
        run: |
          echo "Bundling web assets to web"
          $HOME/.cargo/bin/dx bundle --platform web --release --out-dir web
          ls -la web || true

      - name: Install cargo-chef and prepare recipe
        run: |
          cargo install cargo-chef --locked --force
          cargo chef prepare --recipe-path recipe.json

      - name: Install sccache and cache
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh -o /tmp/install-binstall.sh
          bash /tmp/install-binstall.sh
          cargo binstall sccache
      - name: Cache sccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/sccache
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}

      - name: Set RUSTC_WRAPPER for sccache
        run: |
          echo "RUSTC_WRAPPER=$(which sccache)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Prepare recipe.json for Docker build
        run: |
          # recipe.json is already prepared by cargo chef earlier in this job
          ls -la recipe.json || true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
